---
language: python
python: "2.7"
env:
 - ANSIBLE_VERSION=2.0.0
 - ANSIBLE_VERSION=2.3.0.0
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq python-apt python-pycurl
 - sudo git config --global user.name "root"
 - sudo git config --global user.email root@localhost
install:
  - pip install ansible==$ANSIBLE_VERSION
script:
  - echo localhost > inventory
  - sed -n -e 's/^    //p' README.md > test.yml
  - "printf '[defaults]\nroles_path = ../' > ansible.cfg"
  - ansible-playbook --syntax-check -i inventory test.yml
  - ansible-playbook -i inventory test.yml --connection=local --sudo
  - sudo git -C /etc log
notifications:
  email:
    on_failure: always
    on_success: change
