%YAML 1.1  # roles/etckeeper/tasks/main.yml  -*- mode: yaml -*-

# Ansible role to install, configure, and use etckeeper
---
# tasks file for etckeeper

- name: Install etckeeper
  apt: pkg=etckeeper state=installed
       install_recommends=no
  register: result
  notify: Record changes in etckeeper
  when: install

  # fix `etckeeper unclean` if necessary (from etckeeper.git commit aeb50b5)
- name: Maybe fix etckeeper unclean
  lineinfile: dest=/etc/etckeeper/unclean.d/50test state=present
              regexp=' -d \.git'
              line='       [ -d .git ] && [ -n "`git status --porcelain`" ]'
  notify: Record changes in etckeeper
  when: install

- name: Set etckeeper VCS
  lineinfile: dest=/etc/etckeeper/etckeeper.conf state=present
              regexp='^VCS=' line='VCS={{ etckeeper_vcs }}'
  when: result|changed

- name: Ignore password/group/shadow backups
  lineinfile: dest=/etc/.{{ etckeeper_vcs }}ignore state=present
              line="{{ item }}" create=yes insertafter=EOF
  with_items:
  - '# begin section managed by etckeeper (do not edit this section by hand)'
  - '# end section managed by etckeeper'
  - '# ignore {passwd,group,shadow,gshadow}- backup files'
  - '{% "." if etckeeper_vcs == hg %}*-'
  notify: Record changes in etckeeper

- name: Initialize etckeeper
  command: etckeeper init
           creates=/etc/.git
  notify: Record changes in etckeeper

- name: Record unsaved changes in etckeeper
  shell: "if etckeeper unclean;
          then etckeeper commit '{{ etckeeper_pre_message }}'; fi"
  when: precommit and commit
